In [1]:
import pandas as pd
from pathlib import Path

In [2]:
crowd_df_path = Path(r"C:\Users\Maddy\Desktop\UNI\Homework\PROJECTS\P2\Starter_Files\Resources\crowdfunding.xlsx")
crowd_df = pd.read_excel(crowd_df_path)

In [3]:
crowd_df

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks

In [4]:

unique_values = crowd_df['category & sub-category'].str.split(expand=True).apply(lambda x: tuple(x.unique()), axis=0)
print(unique_values)

0    (food/food, music/rock, technology/web, theate...
1         (trucks, None, &, music, rock, games, books)
2    (None, video/documentary, video/drama, video/a...
3                                      (None, fiction)
dtype: object

In [5]:
#create a list for the column names 
proper_cols=list(crowd_df.columns)[14].split(',')
proper_cols

['category & sub-category']

In [6]:
crowd_df[['category','subcategory']] = crowd_df ["category & sub-category"].str.split('/' , expand=True)
crowd_df.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [7]:
#create a dateframe that has Cat_ids with only Category titles 
categories = crowd_df['category'].unique()

In [8]:
# Create a DataFrame with category_id and category columns
category_df = pd.DataFrame({
    'category_id': [f'Cat{i+1}' for i in range(len(categories))],
    'category': categories
})

category_df

  category_id      category
0        Cat1          food
1        Cat2         music
2        Cat3    technology
3        Cat4       theater
4        Cat5  film & video
5        Cat6    publishing
6        Cat7         games
7        Cat8   photography
8        Cat9    journalism

In [9]:
#convert to csv - Crowdfunding - Cat 
category_df.to_csv('Starter_Files/Resources/Category.csv', index=False)

In [10]:
##SUB-CATEOGRY

In [11]:
#create a dateframe that has Cat_ids with only Category titles 
sub_categories=crowd_df['subcategory'].unique()

In [12]:
# Create a DataFrame with category_id and category columns
sub_categories_df = pd.DataFrame({
    'Sub-category_id': [f'Subcat{i+1}' for i in range(len(sub_categories))],
    'subcategory': sub_categories
})

sub_categories_df

   Sub-category_id        subcategory
0          Subcat1        food trucks
1          Subcat2               rock
2          Subcat3                web
3          Subcat4              plays
4          Subcat5        documentary
5          Subcat6     electric music
6          Subcat7              drama
7          Subcat8         indie rock
8          Subcat9          wearables
9         Subcat10         nonfiction
10        Subcat11          animation
11        Subcat12        video games
12        Subcat13             shorts
13        Subcat14            fiction
14        Subcat15  photography books
15        Subcat16   radio & podcasts
16        Subcat17              metal
17        Subcat18               jazz
18        Subcat19       translations
19        Subcat20         television
20        Subcat21       mobile games
21        Subcat22        world music
22        Subcat23    science fiction
23        Subcat24              audio

In [13]:
#convert to csv - Crowdfunding - SubCat
sub_categories_df.to_csv('Starter_Files/Resources/Sub Category.csv', index=False)

In [14]:
crowd_df.head()

,cf_id,contact_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [21]:
#creating the Dataframe with renmaning changes and datatype changes 


crowd_df.rename(columns={'blurb': 'Description'}, inplace=True)
crowd_df['goal'] = crowd_df['goal'].astype(float)
crowd_df['pledged'] = crowd_df['pledged'].astype(float)
crowd_df.rename(columns={'launched_at': 'launch_date'}, inplace=True)
crowd_df.rename(columns={'deadline': 'end_date'}, inplace=True)

In [45]:
crowd_df['launch_date'] = pd.to_datetime(crowd_df['launch_date'],dayfirst=True, yearfirst=True,format='mixed').dt.strftime('%d-%m-%y')
#crowd_df['end_date'] = pd.to_datetime(crowd_df['end_date'], format='%d-%m-%Y').dt.strftime('%d-%m-%y')

In [32]:
crowd_df

,cf_id,contact_id,company_name,Description,goal,pledged,outcome,backers_count,country,currency,launch_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,4661,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,01d-01m-1970YYY,01-01-1970,False,False,food/food trucks,food,food trucks
1,1621,3765,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,01d-01m-1970YYY,01-01-1970,False,True,music/rock,music,rock
2,1812,4187,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,01d-01m-1970YYY,01-01-1970,False,False,technology/web,technology,web
3,2156,4941,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,01d-01m-1970YYY,01-01-1970,False,False,music/rock,music,rock
4,1365,2199,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,01d-01m-1970YYY,01-01-1970,False,False,theater/plays,theater,plays
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,3684,Manning-Hamilton,Vision-oriented scalable definition,97300.0,153216.0,successful,2043,US,USD,01d-01m-1970YYY,01-01-1970,False,True,food/food trucks,food,food trucks
996,2031,5784,Butler LLC,Future-proofed upward-trending migration,6600.0,4814.0,failed,112,US,USD,01d-01m-1970YYY,01-01-1970,False,False,theater/plays,theater,plays
997,1627,1498,Ball LLC,Right-sized full-range throughput,7600.0,4603.0,canceled,139,IT,EUR,01d-01m-1970YYY,01-01-1970,False,False,theater/plays,theater,plays
998,2175,6073,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600.0,37823.0,failed,374,US,USD,01d-01m-1970YYY,01-01-1970,False,True,music/indie rock,music,indie rock
999,1788,4939,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100.0,62819.0,canceled,1122,US,USD,01d-01m-1970YYY,01-01-1970,False,False,food/food trucks,food,food trucks